package org.synopia.behavior.tree;

/**
 * Callback interface with the method that gets called from the generated byte code.
 * <p/>
 * Created by synopia on 12.07.2014.
 */
public interface Callback {
    BehaviorState execute(int id, BehaviorAction action, String command);

    public static Callback NULL = new Callback() {
        @Override
        public BehaviorState execute(int id, BehaviorAction action, String command) {
            return BehaviorState.UNDEFINED;
        }
    };
}
